[package]
name = "cta"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-gateway = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", }
twilight-http = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", }
twilight-standby = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", }
twilight-model = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", }
twilight-cache-inmemory = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", }
twilight-lavalink = { git = "https://github.com/twilight-rs/twilight/", rev = "1e65bb41503870a8b1d6a6030f7630323a2f2b5c", default-features = false, features = ["native-tls"], }

rustls = { default-features = false, features = ["ring"], version = "0.23" }

http-body-util = "0.1"
hyper = { features = ["server"], version = "1" }
hyper-util = { features = ["http1", "client-legacy"], version = "0.1" }

rustls-webpki = { version = "0.102", features = ["std"] }
reqwest = "0.12.2"
percent-encoding = { version = "2.3.2", optional = true }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next"}

songbird = { git = "https://github.com/jtscuba/songbird", branch = "davey", default-features = false, features = ["driver", "gateway", "twilight", "rustls", "tws"] }
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.2" }

bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1" }

tracing = "0.1"
tracing-subscriber = "0.3"

anyhow = "1.0"

tokio = { version = "1.42.0", features = ["full"] }

nanorand = "*"


[lints.clippy]
correctness = "deny"
suspicious = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"
