[package]
name = "cta"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-gateway = "0.16"
twilight-http = "0.16"
twilight-standby = "0.16"
twilight-model = "0.16"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
